import { Item } from '../types/items';


// Only export ITEM_LIST and any data/constants, all types/schemas are now in types/.

// Example item list
export const ITEM_LIST: Item[] = [
	{
		id: 'healing_potion',
		name: 'Healing Potion',
		description: 'Restores 10 HP.',
		icon: require('../assets/images/items/health-potion.png'),
		slot: 'none',
		usable: true,
	},
	{
		id: 'iron_helmet',
		name: 'Iron Helmet',
		description: 'A sturdy iron helmet.',
		icon: require('../assets/images/gear-slot/helmet.png'),
		slot: 'helmet',
		usable: false,
		stats: { CON: 1 },
	},
	{
		id: 'leather_boots',
		name: 'Leather Boots',
		description: 'Lightweight boots for quick movement.',
		icon: require('../assets/images/items/leather-boots.png'),
		slot: 'boots',
		usable: false,
		stats: { DEX: 1 },
	},
	{
		id: 'rations',
		name: 'Rations',
		description: 'Food and water for one day.',
		icon: require('../assets/images/items/rations.png'),
		slot: 'none',
		usable: false,
	},
	{
		id: 'tent',
		name: 'Tent',
		description: 'A small tent for camping.',
		icon: require('../assets/images/items/tent.png'),
		slot: 'none',
		usable: false,
	},
	{
		id: 'dagger',
		name: 'Dagger',
		description: 'A basic, lightweight weapon.',
		icon: require('../assets/images/items/dagger.png'),
		slot: 'mainHand',
		usable: false,
		stats: { DEX: 1 },
	},
	{
		id: 'staff',
		name: 'Staff',
		description: 'A simple wooden staff.',
		icon: require('../assets/images/items/staff.png'),
		slot: 'mainHand',
		usable: false,
		stats: { INT: 1 },
	},
	{
		id: 'sword',
		name: 'Sword',
		description: 'A basic sword.',
		icon: require('../assets/images/items/short-sword.png'),
		slot: 'mainHand',
		usable: false,
		stats: { STR: 1 },
	},
	{
		id: 'shield',
		name: 'Shield',
		description: 'A basic shield for protection.',
		icon: require('../assets/images/items/iron-shield.png'),
		slot: 'offHand',
		usable: false,
		stats: { CON: 1 },
	},
	{
		id: 'mace',
		name: 'Mace',
		description: 'A simple blunt weapon favored by clerics.',
		icon: require('../assets/images/items/mace.png'),
		slot: 'mainHand',
		usable: false,
		stats: { STR: 1 },
	},
];
