-- Seed initial NPCs
INSERT INTO `npcs` (
	id, slug, name, role, alignment, disposition, description, base_health, base_armor_class,
	challenge_rating, archetype, default_actions, stats, abilities, loot_table, metadata, created_at, updated_at
)
VALUES
	(
		'npc_guard_captain',
		'guard_captain',
		'Town Guard Captain',
		'Sentinel',
		'lawful_good',
		'friendly',
		'A veteran guard tasked with keeping the peace.',
		48,
		18,
		3,
		'guardian',
		'["attack","defend","issue_orders"]',
		'{"strength":16,"dexterity":12,"wisdom":13}',
		'["Commanding Presence","Shield Wall"]',
		'["Halberd","Guard Insignia"]',
		'{"tags":["friendly","quest-giver"]}',
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'npc_merchant_arcanist',
		'merchant_arcanist',
		'Arcanist Merchant',
		'Vendor',
		'neutral',
		'vendor',
		'Travelling mage who barters enchanted items.',
		32,
		14,
		2,
		'support',
		'["barter","cast_minor_spell"]',
		'{"intelligence":17,"charisma":15}',
		'["Identify","Mystic Shield"]',
		'["Potion of Healing","Scroll of Shield"]',
		'{"tags":["vendor","support"]}',
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'npc_goblin_raider',
		'goblin_raider',
		'Goblin Raider',
		'Melee',
		'chaotic_evil',
		'hostile',
		'Sneaky goblin that loves ambushes.',
		18,
		13,
		0.5,
		'skirmisher',
		'["stab","hide"]',
		'{"dexterity":15,"constitution":12}',
		'["Pack Tactics"]',
		'["Rusty Dagger","Coin Pouch"]',
		'{"tags":["hostile","underground"]}',
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'npc_goblin_archer',
		'goblin_archer',
		'Goblin Archer',
		'Ranged',
		'chaotic_evil',
		'hostile',
		'Goblin archer that prefers to attack from a distance.',
		16,
		13,
		0.5,
		'archer',
		'["shoot","aim","retreat"]',
		'{"dexterity":16,"constitution":11}',
		'["Precise Shot","Keen Eye"]',
		'["Shortbow","Arrows","Coin Pouch"]',
		'{"tags":["hostile","underground"]}',
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'npc_goblin_cleric',
		'goblin_cleric',
		'Goblin Cleric',
		'Support',
		'chaotic_evil',
		'hostile',
		'Goblin shaman that heals and supports other goblins.',
		20,
		12,
		0.5,
		'cleric',
		'["heal","bless","smite"]',
		'{"wisdom":14,"constitution":13}',
		'["Healing Word","Divine Protection"]',
		'["Holy Symbol","Healing Potion","Coin Pouch"]',
		'{"tags":["hostile","underground","healer"]}',
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'npc_goblin_scout',
		'goblin_scout',
		'Goblin Scout',
		'Scout',
		'chaotic_evil',
		'hostile',
		'Goblin scout that can trigger alarms to alert others.',
		14,
		14,
		0.5,
		'scout',
		'["alarm","hide","flee"]',
		'{"dexterity":16,"wisdom":13}',
		'["Alert","Alarm Signal"]',
		'["Horn","Coin Pouch"]',
		'{"tags":["hostile","underground","scout"]}',
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	)
ON CONFLICT(id) DO UPDATE SET
	slug = excluded.slug,
	name = excluded.name,
	role = excluded.role,
	alignment = excluded.alignment,
	disposition = excluded.disposition,
	description = excluded.description,
	base_health = excluded.base_health,
	base_armor_class = excluded.base_armor_class,
	challenge_rating = excluded.challenge_rating,
	archetype = excluded.archetype,
	default_actions = excluded.default_actions,
	stats = excluded.stats,
	abilities = excluded.abilities,
	loot_table = excluded.loot_table,
	metadata = excluded.metadata,
	updated_at = excluded.updated_at;

