-- Seed starting location maps for all world × location combinations
INSERT INTO `maps` (
	id, slug, name, description, width, height, default_terrain, fog_of_war, terrain_layers, metadata, generator_preset, seed, theme, biome, world, is_generated, created_at, updated_at
)
VALUES
	(
		'map_faerun_tavern',
		'faerun_tavern',
		'Faerûn Tavern',
		'A bustling inn or tavern, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"tavern","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_cave',
		'faerun_cave',
		'Faerûn Cave',
		'A dark, mysterious cave, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"cave","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_camp',
		'faerun_camp',
		'Faerûn Camp',
		'A wilderness encampment, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"camp","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_palace',
		'faerun_palace',
		'Faerûn Palace',
		'A royal palace or castle, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"palace","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_bedroom',
		'faerun_bedroom',
		'Faerûn Bedroom',
		'A private chamber, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"bedroom","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_ship',
		'faerun_ship',
		'Faerûn Ship',
		'A sea or air vessel, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"ship","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_marketplace',
		'faerun_marketplace',
		'Faerûn Marketplace',
		'A bustling bazaar, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"marketplace","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_temple',
		'faerun_temple',
		'Faerûn Temple',
		'A sacred place of worship, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"temple","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_dungeon',
		'faerun_dungeon',
		'Faerûn Dungeon',
		'A dangerous dungeon, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"dungeon","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_forest',
		'faerun_forest',
		'Faerûn Forest',
		'A mystical grove, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"forest","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_tower',
		'faerun_tower',
		'Faerûn Tower',
		'A wizard''s tower, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"tower","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_arena',
		'faerun_arena',
		'Faerûn Arena',
		'A colosseum for combat, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"arena","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_library',
		'faerun_library',
		'Faerûn Library',
		'A place of knowledge, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"library","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_smithy',
		'faerun_smithy',
		'Faerûn Smithy',
		'A smith''s forge, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"smithy","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_trail',
		'faerun_trail',
		'Faerûn Trail',
		'A trail between cities, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"trail","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_farm',
		'faerun_farm',
		'Faerûn Farm',
		'A rural homestead, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"farm","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_graveyard',
		'faerun_graveyard',
		'Faerûn Graveyard',
		'A crypt or cemetery, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"graveyard","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_faerun_portal',
		'faerun_portal',
		'Faerûn Portal',
		'A magical gate, adapted for the Faerûn setting.',
		28,
		28,
		'{"type":"cobblestone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"faerun","location":"portal","biome":"temperate"}',
		'static',
		'static',
		'medieval',
		'temperate',
		'faerun',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_tavern',
		'eberron_tavern',
		'Eberron Tavern',
		'A bustling inn or tavern, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"tavern","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_cave',
		'eberron_cave',
		'Eberron Cave',
		'A dark, mysterious cave, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"cave","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_camp',
		'eberron_camp',
		'Eberron Camp',
		'A wilderness encampment, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"camp","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_palace',
		'eberron_palace',
		'Eberron Palace',
		'A royal palace or castle, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"palace","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_bedroom',
		'eberron_bedroom',
		'Eberron Bedroom',
		'A private chamber, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"bedroom","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_ship',
		'eberron_ship',
		'Eberron Ship',
		'A sea or air vessel, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"ship","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_marketplace',
		'eberron_marketplace',
		'Eberron Marketplace',
		'A bustling bazaar, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"marketplace","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_temple',
		'eberron_temple',
		'Eberron Temple',
		'A sacred place of worship, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"temple","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_dungeon',
		'eberron_dungeon',
		'Eberron Dungeon',
		'A dangerous dungeon, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"dungeon","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_forest',
		'eberron_forest',
		'Eberron Forest',
		'A mystical grove, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"forest","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_tower',
		'eberron_tower',
		'Eberron Tower',
		'A wizard''s tower, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"tower","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_arena',
		'eberron_arena',
		'Eberron Arena',
		'A colosseum for combat, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"arena","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_library',
		'eberron_library',
		'Eberron Library',
		'A place of knowledge, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"library","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_smithy',
		'eberron_smithy',
		'Eberron Smithy',
		'A smith''s forge, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"smithy","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_trail',
		'eberron_trail',
		'Eberron Trail',
		'A trail between cities, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"trail","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_farm',
		'eberron_farm',
		'Eberron Farm',
		'A rural homestead, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"farm","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_graveyard',
		'eberron_graveyard',
		'Eberron Graveyard',
		'A crypt or cemetery, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"graveyard","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_eberron_portal',
		'eberron_portal',
		'Eberron Portal',
		'A magical gate, adapted for the Eberron setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":false}',
		'[]',
		'{"world":"eberron","location":"portal","biome":"urban"}',
		'static',
		'static',
		'industrial',
		'urban',
		'eberron',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_tavern',
		'underdark_tavern',
		'Underdark Tavern',
		'A bustling inn or tavern, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"tavern","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_cave',
		'underdark_cave',
		'Underdark Cave',
		'A dark, mysterious cave, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"cave","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_camp',
		'underdark_camp',
		'Underdark Camp',
		'A wilderness encampment, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"camp","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_palace',
		'underdark_palace',
		'Underdark Palace',
		'A royal palace or castle, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"palace","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_bedroom',
		'underdark_bedroom',
		'Underdark Bedroom',
		'A private chamber, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"bedroom","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_ship',
		'underdark_ship',
		'Underdark Ship',
		'A sea or air vessel, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"ship","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_marketplace',
		'underdark_marketplace',
		'Underdark Marketplace',
		'A bustling bazaar, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"marketplace","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_temple',
		'underdark_temple',
		'Underdark Temple',
		'A sacred place of worship, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"temple","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_dungeon',
		'underdark_dungeon',
		'Underdark Dungeon',
		'A dangerous dungeon, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"dungeon","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_forest',
		'underdark_forest',
		'Underdark Forest',
		'A mystical grove, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"forest","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_tower',
		'underdark_tower',
		'Underdark Tower',
		'A wizard''s tower, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"tower","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_arena',
		'underdark_arena',
		'Underdark Arena',
		'A colosseum for combat, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"arena","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_library',
		'underdark_library',
		'Underdark Library',
		'A place of knowledge, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"library","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_smithy',
		'underdark_smithy',
		'Underdark Smithy',
		'A smith''s forge, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"smithy","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_trail',
		'underdark_trail',
		'Underdark Trail',
		'A trail between cities, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"trail","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_farm',
		'underdark_farm',
		'Underdark Farm',
		'A rural homestead, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"farm","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_graveyard',
		'underdark_graveyard',
		'Underdark Graveyard',
		'A crypt or cemetery, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"graveyard","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	),
	(
		'map_underdark_portal',
		'underdark_portal',
		'Underdark Portal',
		'A magical gate, adapted for the Underdark setting.',
		28,
		28,
		'{"type":"stone","elevation":0}',
		'{"enabled":true}',
		'[]',
		'{"world":"underdark","location":"portal","biome":"underground"}',
		'static',
		'static',
		'dark',
		'underground',
		'underdark',
		false,
		CAST(unixepoch('subsecond') * 1000 AS INTEGER),
		CAST(unixepoch('subsecond') * 1000 AS INTEGER)
	)
ON CONFLICT(id) DO UPDATE SET
	slug = excluded.slug,
	name = excluded.name,
	description = excluded.description,
	width = excluded.width,
	height = excluded.height,
	default_terrain = excluded.default_terrain,
	fog_of_war = excluded.fog_of_war,
	terrain_layers = excluded.terrain_layers,
	metadata = excluded.metadata,
	generator_preset = excluded.generator_preset,
	seed = excluded.seed,
	theme = excluded.theme,
	biome = excluded.biome,
	world = excluded.world,
	is_generated = excluded.is_generated,
	updated_at = excluded.updated_at;