import { Dimensions, StyleSheet } from 'react-native';

export default StyleSheet.create({
	overlay: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.4)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	modalBox: {
		width: '95%',
		maxWidth: 900,
		borderRadius: 18,
		backgroundColor: '#FFF8E1',
		padding: 24,
		alignItems: 'center',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.18,
		shadowRadius: 10,
		elevation: 8,
		maxHeight: '90%',
	},
	content: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		width: '100%',
		gap: 32,
	},
	title: {
		alignSelf: 'center',
		marginBottom: 18,
		fontSize: 28,
		fontWeight: 'bold',
		color: '#8B2323',
	},
	sheetRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		width: '100%',
		gap: 32,
	},
	leftCol: {
		flex: 1,
		minWidth: 260,
		maxWidth: 340,
		alignItems: 'center',
	},
	portraitBox: {
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 8,
	},
	portrait: {
		width: 120,
		height: 120,
		borderRadius: 12,
		borderWidth: 2,
		borderColor: '#C9B037',
		backgroundColor: '#F9F6EF',
		marginBottom: 8,
	},
	infoRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		marginBottom: 8,
	},
	infoText: {
		fontSize: 16,
		color: '#8B5C2A',
		marginRight: 8,
	},
	nameText: {
		fontSize: 22,
		fontWeight: 'bold',
		color: '#8B2323',
		marginBottom: 8,
		alignSelf: 'center',
	},
	label: {
		fontWeight: 'bold',
		marginTop: 10,
		color: '#8B2323',
		fontSize: 16,
		textAlign: 'center',
		alignSelf: 'center',
	},
	value: {
		marginLeft: 0,
		marginBottom: 4,
		color: '#3B2F1B',
		fontSize: 15,
	},
	hpApRow: {
		flexDirection: 'row',
		gap: 18,
		marginTop: 8,
		marginBottom: 8,
	},
	statText: {
		fontSize: 15,
		color: '#8B2323',
		fontWeight: 'bold',
	},
	inventoryGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		marginTop: 8,
		marginBottom: 8,
		minHeight: 48,
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	inventoryItem: {
		alignItems: 'center',
		marginBottom: 8,
	},
	inventoryIcon: {
		width: 36,
		height: 36,
		marginBottom: 2,
	},
	inventoryName: {
		fontSize: 12,
		color: '#3B2F1B',
		textAlign: 'center',
		maxWidth: 60,
	},
	emptyInventory: {
		color: '#aaa',
		fontStyle: 'italic',
		fontSize: 14,
	},
	rightCol: {
		flex: 1,
		minWidth: 260,
		maxWidth: 340,
		alignItems: 'center',
	},
	statGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		marginTop: 8,
		marginBottom: 8,
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	statBox: {
		alignItems: 'center',
		marginVertical: 0,
		padding: 8,
		borderWidth: 2,
		borderColor: '#8B5C2A',
		borderRadius: 10,
		backgroundColor: '#F9F6EF',
		width: 90,
		marginRight: 8,
		marginBottom: 8,
	},
	statLabel: {
		fontWeight: 'bold',
		fontSize: 15,
		color: '#8B2323',
		marginBottom: 2,
	},
	statValue: {
		fontSize: 18,
		color: '#3B2F1B',
		fontWeight: 'bold',
	},
	skillsGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 16,
		marginTop: 8,
		marginBottom: 8,
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	skillIconCard: {
		width: 60,
		height: 60,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F9F6EF',
		margin: 0,
		padding: 0,
	},
	skillIconFlat: {
		width: 60,
		height: 60,
		resizeMode: 'contain',
	},
	skillName: {
		fontSize: 12,
		color: '#3B2F1B',
		textAlign: 'center',
		marginTop: 2,
		maxWidth: 60,
	},
	emptySkills: {
		color: '#aaa',
		fontStyle: 'italic',
		fontSize: 14,
	},
	closeButton: {
		backgroundColor: '#C9B037',
		paddingVertical: 10,
		paddingHorizontal: 32,
		borderRadius: 8,
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: 100,
	},
	closeButtonText: {
		color: '#3B2F1B',
		fontWeight: 'bold',
		fontSize: 16,
	},
	portraitPinned: {
		position: 'absolute',
		top: 24,
		left: 24,
		zIndex: 20,
	},
	portraitLarge: {
		width: 180,
		height: 180,
		borderRadius: 24,
		borderWidth: 3,
		borderColor: '#C9B037',
		backgroundColor: '#F9F6EF',
	},
	contentWithPortrait: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		width: '100%',
	},
	skillIconWrapper: {
		width: 72,
		height: 72,
		alignItems: 'center',
		justifyContent: 'center',
		margin: 0,
		padding: 0,
		position: 'relative',
	},
	skillIconLarge: {
		width: 64,
		height: 64,
		resizeMode: 'contain',
	},
	tooltip: {
		position: 'absolute',
		bottom: 76,
		left: '50%',
		transform: [{ translateX: -50 }],
		backgroundColor: '#3B2F1B',
		paddingVertical: 4,
		paddingHorizontal: 12,
		borderRadius: 8,
		zIndex: 100,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.18,
		shadowRadius: 6,
		elevation: 4,
	},
	tooltipText: {
		color: '#FFF8E1',
		fontSize: 12,
		fontWeight: 'bold',
		textAlign: 'center',
		maxWidth: 60,
	},
	statGridBelowPortrait: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		marginTop: 8,
		marginBottom: 8,
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	gearGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 16,
		marginTop: 8,
		marginBottom: 8,
		alignItems: 'center',
		justifyContent: 'center',
	},
	gearSlot: {
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 8,
		minWidth: 60,
	},
	gearSlotActive: {
		borderWidth: 3,
		borderColor: '#C9B037',
	},
	gearIcon: {
		width: 48,
		height: 48,
		marginBottom: 4,
		alignSelf: 'center',
	},
	gearLabel: {
		fontSize: 12,
		color: '#3B2F1B',
		textAlign: 'center',
		maxWidth: 80,
		alignSelf: 'center',
	},
	gearCharLayout: {
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: 8,
		marginBottom: 8,
	},
	gearRowCenter: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 12,
	},
	gearRowArmsChest: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 12,
	},
	gearSlotArm: {
		width: 60,
		height: 60,
	},
	gearSlotChest: {
		width: 60,
		height: 60,
	},
	gearColArmHand: {
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 8,
	},
	gearSlotHand: {
		width: 60,
		height: 60,
	},
	unequipButton: {
		backgroundColor: '#C9B037',
		paddingVertical: 8,
		paddingHorizontal: 16,
		borderRadius: 8,
		marginBottom: 8,
	},
	unequipButtonText: {
		color: '#3B2F1B',
		fontWeight: 'bold',
		fontSize: 14,
	},
	centerCol: {
		flex: 1,
		minWidth: 260,
		maxWidth: 340,
		alignItems: 'center',
	},
	inventoryGridCenter: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		marginTop: 8,
		marginBottom: 8,
		minHeight: 48,
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	inventoryItemBox: {
		alignItems: 'center',
		marginRight: 12,
		marginBottom: 8,
		borderWidth: 1,
		borderColor: '#8B5C2A',
		borderStyle: 'dashed',
		borderRadius: 8,
		padding: 8,
	},
	inventoryIconLarge: {
		width: 48,
		height: 48,
		marginBottom: 2,
	},
	infoBlock: {
		backgroundColor: '#F9F6EF',
		borderRadius: 10,
		padding: 12,
		marginBottom: 16,
		width: '100%',
		alignItems: 'center',
	},
	tooltipOverlay: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		alignItems: 'center',
		justifyContent: 'center',
		zIndex: 1,
	},
	tooltipOverIconBg: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: 'rgba(0,0,0,0.5)',
		borderRadius: 8,
	},
	tooltipOverIconLabel: {
		position: 'relative',
		zIndex: 2,
	},
	inventoryItemEquipped: {
		borderWidth: 3,
		borderColor: '#C9B037',
		backgroundColor: '#FFF8E1',
	},
	inventoryItemIncompatible: {
		opacity: 0.4,
		backgroundColor: '#F5F5F5',
	},
	equippedIndicator: {
		position: 'absolute',
		top: 2,
		right: 2,
		backgroundColor: '#C9B037',
		borderRadius: 8,
		width: 16,
		height: 16,
		alignItems: 'center',
		justifyContent: 'center',
	},
	equippedText: {
		color: '#3B2F1B',
		fontSize: 12,
		fontWeight: 'bold',
	},
	gearSlotActions: {
		marginTop: 12,
		padding: 12,
		backgroundColor: '#F9F6EF',
		borderRadius: 8,
		alignItems: 'center',
	},
	gearSlotInstructions: {
		fontSize: 14,
		color: '#8B5C2A',
		textAlign: 'center',
		marginBottom: 8,
	},
	// Mobile responsive styles
	modalBoxMobile: {
		width: '95%',
		maxWidth: '95%',
		maxHeight: '95%',
		padding: 16,
	},
	contentMobile: {
		flexDirection: 'column',
		alignItems: 'stretch',
		width: '100%',
	},
	sheetColumn: {
		flexDirection: 'column',
		alignItems: 'stretch',
		width: '100%',
		gap: 24,
	},
	mobileSection: {
		width: Dimensions.get('window').width - 64,
		alignItems: 'center',
		justifyContent: 'center',
		padding: 0,
		margin: 0,
		marginBottom: 24,
	},
	portraitMobile: {
		width: 120,
		height: 120,
		borderRadius: 16,
		borderWidth: 2,
		borderColor: '#C9B037',
		backgroundColor: '#F9F6EF',
	},
	statGridMobile: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		marginTop: 8,
		marginBottom: 8,
		alignItems: 'center',
		justifyContent: 'center',
		maxWidth: '100%',
	},
	statBoxMobile: {
		alignItems: 'center',
		marginVertical: 0,
		padding: 6,
		borderWidth: 2,
		borderColor: '#8B5C2A',
		borderRadius: 8,
		backgroundColor: '#F9F6EF',
		width: 70,
		marginRight: 6,
		marginBottom: 6,
	},
	inventoryGridMobile: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		marginTop: 8,
		marginBottom: 8,
		minHeight: 48,
		alignItems: 'center',
		justifyContent: 'center',
		maxWidth: '100%',
	},
	inventoryItemBoxMobile: {
		alignItems: 'center',
		marginRight: 8,
		marginBottom: 8,
		borderWidth: 1,
		borderColor: '#8B5C2A',
		borderStyle: 'dashed',
		borderRadius: 8,
		padding: 12,
		minWidth: 64,
		minHeight: 64,
	},
	closeButtonMobile: {
		backgroundColor: '#C9B037',
		paddingVertical: 12,
		paddingHorizontal: 24,
		borderRadius: 8,
		minHeight: 48, // Better touch target
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	// Button row styles
	buttonRow: {
		flexDirection: 'row',
		gap: 16,
		marginTop: 24,
		alignItems: 'center',
		justifyContent: 'center',
	},
	buttonRowMobile: {
		flexDirection: 'row',
		gap: 8,
		marginTop: 16,
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	actionButton: {
		backgroundColor: '#E2D3B3',
		paddingVertical: 10,
		paddingHorizontal: 16,
		borderRadius: 8,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: 100,
	},
	actionButtonMobile: {
		backgroundColor: '#E2D3B3',
		paddingVertical: 12,
		paddingHorizontal: 12,
		borderRadius: 8,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		flex: 1,
		minHeight: 48,
	},
	actionButtonText: {
		color: '#3B2F1B',
		fontWeight: 'bold',
		fontSize: 14,
	},
	spellListContainer: {
		flexDirection: 'column',
		gap: 8,
		marginTop: 8,
		marginBottom: 8,
		maxHeight: 300,
	},
	spellItem: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		padding: 12,
		borderWidth: 1,
		borderColor: '#8B5C2A',
		borderRadius: 8,
		backgroundColor: '#F9F6EF',
		marginBottom: 4,
	},
	spellItemPrepared: {
		backgroundColor: '#FFF8E1',
		borderWidth: 2,
		borderColor: '#C9B037',
	},
	spellName: {
		fontSize: 14,
		fontWeight: 'bold',
		color: '#3B2F1B',
		flex: 1,
	},
	spellNamePrepared: {
		color: '#8B2323',
	},
	spellLevel: {
		fontSize: 12,
		color: '#8B5C2A',
		marginLeft: 8,
	},
	spellPreparedMark: {
		fontSize: 18,
		color: '#C9B037',
		fontWeight: 'bold',
		marginLeft: 8,
	},
});
