import { StyleSheet } from 'react-native';

import { DnDTheme } from './dnd-theme';

const fantasyFont = 'Papyrus, Cochin, Copperplate, "Segoe Script", "Comic Sans MS", cursive';
const detailFont = 'Arial, Helvetica, sans-serif';

export const newGameStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: DnDTheme.parchment,
		padding: 24,
		borderWidth: 4,
		borderColor: DnDTheme.borderBrown,
		borderRadius: 18,
		shadowColor: DnDTheme.borderBrown,
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.18,
		shadowRadius: 12,
	},
	scrollViewContent: {
		flexGrow: 1,
	},
	title: {
		fontSize: 32,
		fontWeight: 'bold',
		color: DnDTheme.deepRed,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 12,
		textShadowColor: DnDTheme.gold,
		textShadowOffset: { width: 2, height: 2 },
		textShadowRadius: 2,
	},
	subtitle: {
		fontSize: 22,
		color: DnDTheme.gold,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 10,
		textShadowColor: DnDTheme.borderBrown,
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	label: {
		fontSize: 16,
		color: DnDTheme.textDark,
		fontFamily: fantasyFont,
		marginBottom: 4,
	},
	input: {
		height: 40,
		borderColor: DnDTheme.borderBrown,
		borderWidth: 2,
		borderRadius: 8,
		backgroundColor: DnDTheme.sectionBg,
		fontFamily: detailFont,
		fontSize: 16,
		color: DnDTheme.textDark,
		marginBottom: 12,
		paddingHorizontal: 10,
	},
	sectionTitle: {
		fontSize: 18,
		color: DnDTheme.deepRed,
		fontFamily: fantasyFont,
		marginTop: 18,
		marginBottom: 8,
		borderBottomWidth: 2,
		borderBottomColor: DnDTheme.gold,
		paddingBottom: 4,
	},
	sectionBox: {
		backgroundColor: DnDTheme.sectionBg,
		borderWidth: 2,
		borderColor: DnDTheme.borderBrown,
		borderRadius: 10,
		padding: 12,
		marginBottom: 16,
		shadowColor: DnDTheme.borderBrown,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.08,
		shadowRadius: 4,
	},
	infoText: {
		fontSize: 14,
		color: DnDTheme.textDark,
		fontFamily: detailFont,
		marginBottom: 10,
	},
	textArea: {
		minHeight: 200,
		maxHeight: 400,
		height: 250,
		textAlignVertical: 'top',
		fontFamily: detailFont,
		fontSize: 18,
		color: DnDTheme.textDark,
		backgroundColor: DnDTheme.sectionBg,
		borderColor: DnDTheme.borderBrown,
		borderWidth: 2,
		borderRadius: 8,
		padding: 16,
		lineHeight: 26,
	},
	divider: {
		height: 2,
		backgroundColor: DnDTheme.borderBrown,
		marginVertical: 16,
		borderRadius: 1,
	},
	wizardNavigation: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginTop: 20,
		marginBottom: 10,
		paddingHorizontal: 20,
	},
	stepIndicator: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 20,
		paddingHorizontal: 10,
	},
	stepDot: {
		width: 12,
		height: 12,
		borderRadius: 6,
		backgroundColor: DnDTheme.borderBrown,
		marginHorizontal: 4,
	},
	stepDotActive: {
		backgroundColor: DnDTheme.gold,
		width: 14,
		height: 14,
		borderRadius: 7,
	},
	stepDotCompleted: {
		backgroundColor: DnDTheme.deepRed,
	},
	stepLine: {
		height: 2,
		backgroundColor: DnDTheme.borderBrown,
		flex: 1,
		marginHorizontal: 8,
	},
	stepLineCompleted: {
		backgroundColor: DnDTheme.deepRed,
	},
	wizardHeader: {
		backgroundColor: DnDTheme.sectionBg,
		borderWidth: 2,
		borderColor: DnDTheme.borderBrown,
		borderRadius: 10,
		padding: 16,
		marginBottom: 20,
		shadowColor: DnDTheme.borderBrown,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
	},
	wizardStepTitle: {
		fontSize: 20,
		color: DnDTheme.deepRed,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 8,
	},
	wizardStepSubtitle: {
		fontSize: 14,
		color: DnDTheme.textDark,
		fontFamily: detailFont,
		textAlign: 'center',
		opacity: 0.8,
	},
	// Mobile responsive styles
	containerMobile: {
		padding: 0,
	},
	scrollViewContentMobile: {
		paddingLeft: 0,
		paddingRight: 0,
		marginLeft: 0,
		marginRight: 0,
		paddingBottom: 20,
	},
	stepIndicatorMobile: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 16,
		paddingHorizontal: 8,
		flexWrap: 'wrap',
	},
	stepDotMobile: {
		width: 10,
		height: 10,
		borderRadius: 5,
		backgroundColor: DnDTheme.borderBrown,
		marginHorizontal: 3,
	},
	stepDotActiveMobile: {
		backgroundColor: DnDTheme.gold,
		width: 12,
		height: 12,
		borderRadius: 6,
	},
	stepLineMobile: {
		height: 2,
		backgroundColor: DnDTheme.borderBrown,
		flex: 1,
		marginHorizontal: 4,
		minWidth: 20,
		maxWidth: 40,
	},
	sectionBoxMobile: {
		backgroundColor: DnDTheme.sectionBg,
		padding: 0,
		marginBottom: 12,
		shadowColor: DnDTheme.borderBrown,
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.06,
		shadowRadius: 2,
	},
	titleMobile: {
		fontSize: 24,
		fontWeight: 'bold',
		color: DnDTheme.deepRed,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 8,
		textShadowColor: DnDTheme.gold,
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	subtitleMobile: {
		fontSize: 18,
		color: DnDTheme.gold,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 8,
		textShadowColor: DnDTheme.borderBrown,
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	// Add submit button styles for forms
	submitButton: {
		backgroundColor: DnDTheme.gold,
		paddingVertical: 10,
		paddingHorizontal: 24,
		borderRadius: 8,
		marginTop: 8,
		alignItems: 'center',
	},
	submitButtonDisabled: {
		backgroundColor: DnDTheme.parchmentDark,
		paddingVertical: 10,
		paddingHorizontal: 24,
		borderRadius: 8,
		marginTop: 8,
		alignItems: 'center',
	},
	submitButtonText: {
		color: DnDTheme.textDark,
		fontWeight: 'bold',
		fontSize: 16,
		fontFamily: fantasyFont,
	},
});
