import { StyleSheet } from 'react-native';

import { DnDTheme } from './dnd-theme';

const fantasyFont = 'Papyrus, Cochin, Copperplate, "Segoe Script", "Comic Sans MS", cursive';
const detailFont = 'Arial, Helvetica, sans-serif';

export const setupStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: DnDTheme.parchment,
		padding: 24,
		borderWidth: 4,
		borderColor: DnDTheme.borderBrown,
		borderRadius: 18,
		shadowColor: DnDTheme.borderBrown,
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.18,
		shadowRadius: 12,
	},
	scrollViewContent: {
		flexGrow: 1,
	},
	title: {
		fontSize: 32,
		fontWeight: 'bold',
		color: DnDTheme.deepRed,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 12,
		textShadowColor: DnDTheme.gold,
		textShadowOffset: { width: 2, height: 2 },
		textShadowRadius: 2,
	},
	subtitle: {
		fontSize: 22,
		color: DnDTheme.gold,
		fontFamily: fantasyFont,
		textAlign: 'center',
		marginBottom: 10,
		textShadowColor: DnDTheme.borderBrown,
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	label: {
		fontSize: 16,
		color: DnDTheme.textDark,
		fontFamily: fantasyFont,
		marginBottom: 4,
	},
	input: {
		height: 40,
		borderColor: DnDTheme.borderBrown,
		borderWidth: 2,
		borderRadius: 8,
		backgroundColor: DnDTheme.sectionBg,
		fontFamily: detailFont,
		fontSize: 16,
		color: DnDTheme.textDark,
		marginBottom: 12,
		paddingHorizontal: 10,
	},
	sectionTitle: {
		fontSize: 18,
		color: DnDTheme.deepRed,
		fontFamily: fantasyFont,
		marginTop: 18,
		marginBottom: 8,
		borderBottomWidth: 2,
		borderBottomColor: DnDTheme.gold,
		paddingBottom: 4,
	},
	sectionBox: {
		backgroundColor: DnDTheme.sectionBg,
		borderWidth: 2,
		borderColor: DnDTheme.borderBrown,
		borderRadius: 10,
		padding: 12,
		marginBottom: 16,
		shadowColor: DnDTheme.borderBrown,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.08,
		shadowRadius: 4,
	},
	infoText: {
		fontSize: 14,
		color: DnDTheme.textDark,
		fontFamily: detailFont,
		marginBottom: 10,
	},
	textArea: {
		height: 100,
		textAlignVertical: 'top',
		fontFamily: detailFont,
		fontSize: 16,
		color: DnDTheme.textDark,
		backgroundColor: DnDTheme.sectionBg,
		borderColor: DnDTheme.borderBrown,
		borderWidth: 2,
		borderRadius: 8,
		padding: 10,
	},
	divider: {
		height: 2,
		backgroundColor: DnDTheme.borderBrown,
		marginVertical: 16,
		borderRadius: 1,
	},
});
